# Generated by Erlang.mk. Edit at your own risk!

src/follow_handler.erl:: src/twitter.erl; @touch $@
src/hello_handler.erl:: src/twitter.erl; @touch $@
src/login_handler.erl:: src/twitter.erl; @touch $@
src/logout_handler.erl:: src/twitter.erl; @touch $@
src/mention_handler.erl:: src/twitter.erl; @touch $@
src/register_handler.erl:: src/twitter.erl; @touch $@
src/retweet_handler.erl:: src/twitter.erl; @touch $@
src/search_handler.erl:: src/twitter.erl; @touch $@
src/tweet_handler.erl:: src/twitter.erl; @touch $@

COMPILE_FIRST += twitter
